events {
    worker_connections 1024;
}

http {
    server {
        listen 8080;
        server_name localhost;

        location /api/dummy {
            default_type application/json;
            add_header 'Access-Control-Allow-Origin' '*';
            return 200 '{"status": "success", "message": "Nginx stress test API is active"}';
        }
    }
}
